### ISSUE TITLE
fontconvert: created fonts look terrible 

### ISSUE THREAD

**Issue by elFallino** [adafruit/Adafruit-GFX-Library#103]
Hi,

to have some german umlaut characters I used the fontconvert tool (on windows, minGW, freefonts2.7 following fontconvert_win.md) to convert FreeSans.

How ever, results do work but look very ugly. They look as if their width does not match and therefore are jolted (or compressed/forged - not sure how to translate).
When I try to convert the same TTF with default settings (witch *should* create the same *.h file as shipped) the result is a bit different and looks ugly, too.

Both files differ in size:

Creating a 9pt header results in an reported estimated size "// Approx. 1801 bytes" while the original file reports "// Approx. 1822 bytes"

**Comment by pljakobs** [comment]
Hi elFallino, my original work was to exactly enable international (well, in my case, German) character sets which requires larger font tables. When this was picked up by Adafruit, they decided to settle for 7 bit characters for now, mainly because 8 bit would require up to twice the memory space plus character mapping - if we do it, we don't just want to enable German characters, but ideally all iso8859 character tables. I have not yet had the time to come up with a good idea on how to implement this, but I certainly have the need, so while I won't give an ETA, it will arrive at some point.
regards,

pj

**Comment by elFallino** [comment]
Great. Let me know if I can assist you somehow. (testing, coding, share ideas).
You can contact me in German if you like to ;)

Am 7. Januar 2017 13:10:59 MEZ schrieb Peter Jakobs <notifications@github.com>:
>Hi elFallino, my original work was to exactly enable international
>(well, in my case, German) character sets which requires larger font
>tables. When this was picked up by Adafruit, they decided to settle for
>7 bit characters for now, mainly because 8 bit would require up to
>twice the memory space plus character mapping - if we do it, we don't
>just want to enable German characters, but ideally all iso8859
>character tables. I have not yet had the time to come up with a good
>idea on how to implement this, but I certainly have the need, so while
>I won't give an ETA, it will arrive at some point.
>regards,
>
>pj
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/adafruit/Adafruit-GFX-Library/issues/103#issuecomment-271080047

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pljakobs** [comment]
Let's keep this in English in case someone else wants to chime in

Here's my idea: 
ISO8859 encoding is identical for the lower 7 bits, so that can stay the same, above that, from 0xA0 to 0xFF is where the different encodings differ. See https://de.wikipedia.org/wiki/ISO_8859#Tabelle_der_regionalen_Sonderzeichen
To enable GFXLibrary to use 8 bit fonts, we need to 

- modify fontconvert to encode 8-bit fonts for different encodings using utf->iso8859 mapping
- modify GFXLibrary to use those fonts by mapping the incoming utf8 strings to is8859 characters

The latter is the rather more difficult bit, since this mapping is, for most iso8859 mappings, not mathematical, so it would require rather large conditional structures.
A while ago, I wrote a simple script that uses iconv to generate c-structures for this mapping, but of course, it's impractical to have an array of 2^16 values of which all but 192 are NUL.

I think the write() function would be the right place to do the utf->iso8859 mapping.
Also, I think there should be a way of stating at compile time what iso mapping should be used, that could then a) include the correct fonts (if they are named according to a convention) and b) enable a utf->iso8859 function for the desired mapping. This way, we would not have to carry all the mapping code in the binary.

an initial discussion was [here ](https://github.com/adafruit/Adafruit-GFX-Library/issues/64)

So you see, my thought process is far from finished, other projects have side-dragged me, but I wouldn't mind moving ahead with this.

these are my initial iso8859-x to utf conversion tables:

`
/*
 * converting iso8859-1
 */
int iso8859-1[]={
0xc2a0, 0xc2a1, 0xc2a2, 0xc2a3, 0xc2a4, 0xc2a5, 0xc2a6, 0xc2a7
0xc2a8, 0xc2a9, 0xc2aa, 0xc2ab, 0xc2ac, 0xc2ad, 0xc2ae, 0xc2af
0xc2b0, 0xc2b1, 0xc2b2, 0xc2b3, 0xc2b4, 0xc2b5, 0xc2b6, 0xc2b7
0xc2b8, 0xc2b9, 0xc2ba, 0xc2bb, 0xc2bc, 0xc2bd, 0xc2be, 0xc2bf
0xc380, 0xc381, 0xc382, 0xc383, 0xc384, 0xc385, 0xc386, 0xc387
0xc388, 0xc389, 0xc38a, 0xc38b, 0xc38c, 0xc38d, 0xc38e, 0xc38f
0xc390, 0xc391, 0xc392, 0xc393, 0xc394, 0xc395, 0xc396, 0xc397
0xc398, 0xc399, 0xc39a, 0xc39b, 0xc39c, 0xc39d, 0xc39e, 0xc39f
0xc3a0, 0xc3a1, 0xc3a2, 0xc3a3, 0xc3a4, 0xc3a5, 0xc3a6, 0xc3a7
0xc3a8, 0xc3a9, 0xc3aa, 0xc3ab, 0xc3ac, 0xc3ad, 0xc3ae, 0xc3af
0xc3b0, 0xc3b1, 0xc3b2, 0xc3b3, 0xc3b4, 0xc3b5, 0xc3b6, 0xc3b7
0xc3b8, 0xc3b9, 0xc3ba, 0xc3bb, 0xc3bc, 0xc3bd, 0xc3be, 0xc3bf
};

/*
 * converting iso8859-2
 */
int iso8859-2[]={
0xc2a0, 0xc484, 0xcb98, 0xc581, 0xc2a4, 0xc4bd, 0xc59a, 0xc2a7
0xc2a8, 0xc5a0, 0xc59e, 0xc5a4, 0xc5b9, 0xc2ad, 0xc5bd, 0xc5bb
0xc2b0, 0xc485, 0xcb9b, 0xc582, 0xc2b4, 0xc4be, 0xc59b, 0xcb87
0xc2b8, 0xc5a1, 0xc59f, 0xc5a5, 0xc5ba, 0xcb9d, 0xc5be, 0xc5bc
0xc594, 0xc381, 0xc382, 0xc482, 0xc384, 0xc4b9, 0xc486, 0xc387
0xc48c, 0xc389, 0xc498, 0xc38b, 0xc49a, 0xc38d, 0xc38e, 0xc48e
0xc490, 0xc583, 0xc587, 0xc393, 0xc394, 0xc590, 0xc396, 0xc397
0xc598, 0xc5ae, 0xc39a, 0xc5b0, 0xc39c, 0xc39d, 0xc5a2, 0xc39f
0xc595, 0xc3a1, 0xc3a2, 0xc483, 0xc3a4, 0xc4ba, 0xc487, 0xc3a7
0xc48d, 0xc3a9, 0xc499, 0xc3ab, 0xc49b, 0xc3ad, 0xc3ae, 0xc48f
0xc491, 0xc584, 0xc588, 0xc3b3, 0xc3b4, 0xc591, 0xc3b6, 0xc3b7
0xc599, 0xc5af, 0xc3ba, 0xc5b1, 0xc3bc, 0xc3bd, 0xc5a3, 0xcb99
};

/*
 * converting iso8859-3
 */
int iso8859-3[]={
0xc2a0, 0xc4a6, 0xcb98, 0xc2a3, 0xc2a4, 0x0000, 0xc4a4, 0xc2a7
0xc2a8, 0xc4b0, 0xc59e, 0xc49e, 0xc4b4, 0xc2ad, 0x0000, 0xc5bb
0xc2b0, 0xc4a7, 0xc2b2, 0xc2b3, 0xc2b4, 0xc2b5, 0xc4a5, 0xc2b7
0xc2b8, 0xc4b1, 0xc59f, 0xc49f, 0xc4b5, 0xc2bd, 0x0000, 0xc5bc
0xc380, 0xc381, 0xc382, 0x0000, 0xc384, 0xc48a, 0xc488, 0xc387
0xc388, 0xc389, 0xc38a, 0xc38b, 0xc38c, 0xc38d, 0xc38e, 0xc38f
0x0000, 0xc391, 0xc392, 0xc393, 0xc394, 0xc4a0, 0xc396, 0xc397
0xc49c, 0xc399, 0xc39a, 0xc39b, 0xc39c, 0xc5ac, 0xc59c, 0xc39f
0xc3a0, 0xc3a1, 0xc3a2, 0x0000, 0xc3a4, 0xc48b, 0xc489, 0xc3a7
0xc3a8, 0xc3a9, 0xc3aa, 0xc3ab, 0xc3ac, 0xc3ad, 0xc3ae, 0xc3af
0x0000, 0xc3b1, 0xc3b2, 0xc3b3, 0xc3b4, 0xc4a1, 0xc3b6, 0xc3b7
0xc49d, 0xc3b9, 0xc3ba, 0xc3bb, 0xc3bc, 0xc5ad, 0xc59d, 0xcb99
};

/*
 * converting iso8859-4
 */
int iso8859-4[]={
0xc2a0, 0xc484, 0xc4b8, 0xc596, 0xc2a4, 0xc4a8, 0xc4bb, 0xc2a7
0xc2a8, 0xc5a0, 0xc492, 0xc4a2, 0xc5a6, 0xc2ad, 0xc5bd, 0xc2af
0xc2b0, 0xc485, 0xcb9b, 0xc597, 0xc2b4, 0xc4a9, 0xc4bc, 0xcb87
0xc2b8, 0xc5a1, 0xc493, 0xc4a3, 0xc5a7, 0xc58a, 0xc5be, 0xc58b
0xc480, 0xc381, 0xc382, 0xc383, 0xc384, 0xc385, 0xc386, 0xc4ae
0xc48c, 0xc389, 0xc498, 0xc38b, 0xc496, 0xc38d, 0xc38e, 0xc4aa
0xc490, 0xc585, 0xc58c, 0xc4b6, 0xc394, 0xc395, 0xc396, 0xc397
0xc398, 0xc5b2, 0xc39a, 0xc39b, 0xc39c, 0xc5a8, 0xc5aa, 0xc39f
0xc481, 0xc3a1, 0xc3a2, 0xc3a3, 0xc3a4, 0xc3a5, 0xc3a6, 0xc4af
0xc48d, 0xc3a9, 0xc499, 0xc3ab, 0xc497, 0xc3ad, 0xc3ae, 0xc4ab
0xc491, 0xc586, 0xc58d, 0xc4b7, 0xc3b4, 0xc3b5, 0xc3b6, 0xc3b7
0xc3b8, 0xc5b3, 0xc3ba, 0xc3bb, 0xc3bc, 0xc5a9, 0xc5ab, 0xcb99
};

/*
 * converting iso8859-5
 */
int iso8859-5[]={
0xc2a0, 0xd081, 0xd082, 0xd083, 0xd084, 0xd085, 0xd086, 0xd087
0xd088, 0xd089, 0xd08a, 0xd08b, 0xd08c, 0xc2ad, 0xd08e, 0xd08f
0xd090, 0xd091, 0xd092, 0xd093, 0xd094, 0xd095, 0xd096, 0xd097
0xd098, 0xd099, 0xd09a, 0xd09b, 0xd09c, 0xd09d, 0xd09e, 0xd09f
0xd0a0, 0xd0a1, 0xd0a2, 0xd0a3, 0xd0a4, 0xd0a5, 0xd0a6, 0xd0a7
0xd0a8, 0xd0a9, 0xd0aa, 0xd0ab, 0xd0ac, 0xd0ad, 0xd0ae, 0xd0af
0xd0b0, 0xd0b1, 0xd0b2, 0xd0b3, 0xd0b4, 0xd0b5, 0xd0b6, 0xd0b7
0xd0b8, 0xd0b9, 0xd0ba, 0xd0bb, 0xd0bc, 0xd0bd, 0xd0be, 0xd0bf
0xd180, 0xd181, 0xd182, 0xd183, 0xd184, 0xd185, 0xd186, 0xd187
0xd188, 0xd189, 0xd18a, 0xd18b, 0xd18c, 0xd18d, 0xd18e, 0xd18f
0xe28496, 0xd191, 0xd192, 0xd193, 0xd194, 0xd195, 0xd196, 0xd197
0xd198, 0xd199, 0xd19a, 0xd19b, 0xd19c, 0xc2a7, 0xd19e, 0xd19f
};

/*
 * converting iso8859-6
 */
int iso8859-6[]={
0xc2a0, 0x0000, 0x0000, 0x0000, 0xc2a4, 0x0000, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0xd88c, 0xc2ad, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0xd89b, 0x0000, 0x0000, 0x0000, 0xd89f
0x0000, 0xd8a1, 0xd8a2, 0xd8a3, 0xd8a4, 0xd8a5, 0xd8a6, 0xd8a7
0xd8a8, 0xd8a9, 0xd8aa, 0xd8ab, 0xd8ac, 0xd8ad, 0xd8ae, 0xd8af
0xd8b0, 0xd8b1, 0xd8b2, 0xd8b3, 0xd8b4, 0xd8b5, 0xd8b6, 0xd8b7
0xd8b8, 0xd8b9, 0xd8ba, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
0xd980, 0xd981, 0xd982, 0xd983, 0xd984, 0xd985, 0xd986, 0xd987
0xd988, 0xd989, 0xd98a, 0xd98b, 0xd98c, 0xd98d, 0xd98e, 0xd98f
0xd990, 0xd991, 0xd992, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

/*
 * converting iso8859-7
 */
int iso8859-7[]={
0xc2a0, 0xe28098, 0xe28099, 0xc2a3, 0xe282ac, 0xe282af, 0xc2a6, 0xc2a7
0xc2a8, 0xc2a9, 0xcdba, 0xc2ab, 0xc2ac, 0xc2ad, 0x0000, 0xe28095
0xc2b0, 0xc2b1, 0xc2b2, 0xc2b3, 0xce84, 0xce85, 0xce86, 0xc2b7
0xce88, 0xce89, 0xce8a, 0xc2bb, 0xce8c, 0xc2bd, 0xce8e, 0xce8f
0xce90, 0xce91, 0xce92, 0xce93, 0xce94, 0xce95, 0xce96, 0xce97
0xce98, 0xce99, 0xce9a, 0xce9b, 0xce9c, 0xce9d, 0xce9e, 0xce9f
0xcea0, 0xcea1, 0x0000, 0xcea3, 0xcea4, 0xcea5, 0xcea6, 0xcea7
0xcea8, 0xcea9, 0xceaa, 0xceab, 0xceac, 0xcead, 0xceae, 0xceaf
0xceb0, 0xceb1, 0xceb2, 0xceb3, 0xceb4, 0xceb5, 0xceb6, 0xceb7
0xceb8, 0xceb9, 0xceba, 0xcebb, 0xcebc, 0xcebd, 0xcebe, 0xcebf
0xcf80, 0xcf81, 0xcf82, 0xcf83, 0xcf84, 0xcf85, 0xcf86, 0xcf87
0xcf88, 0xcf89, 0xcf8a, 0xcf8b, 0xcf8c, 0xcf8d, 0xcf8e, 0x0000
};

/*
 * converting iso8859-8
 */
int iso8859-8[]={
0xc2a0, 0x0000, 0xc2a2, 0xc2a3, 0xc2a4, 0xc2a5, 0xc2a6, 0xc2a7
0xc2a8, 0xc2a9, 0xc397, 0xc2ab, 0xc2ac, 0xc2ad, 0xc2ae, 0xc2af
0xc2b0, 0xc2b1, 0xc2b2, 0xc2b3, 0xc2b4, 0xc2b5, 0xc2b6, 0xc2b7
0xc2b8, 0xc2b9, 0xc3b7, 0xc2bb, 0xc2bc, 0xc2bd, 0xc2be, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0xe28097
0xd790, 0xd791, 0xd792, 0xd793, 0xd794, 0xd795, 0xd796, 0xd797
0xd798, 0xd799, 0xd79a, 0xd79b, 0xd79c, 0xd79d, 0xd79e, 0xd79f
0xd7a0, 0xd7a1, 0xd7a2, 0xd7a3, 0xd7a4, 0xd7a5, 0xd7a6, 0xd7a7
0xd7a8, 0xd7a9, 0xd7aa, 0x0000, 0x0000, 0xe2808e, 0xe2808f, 0x0000
};

/*
 * converting iso8859-9
 */
int iso8859-9[]={
0xc2a0, 0xc2a1, 0xc2a2, 0xc2a3, 0xc2a4, 0xc2a5, 0xc2a6, 0xc2a7
0xc2a8, 0xc2a9, 0xc2aa, 0xc2ab, 0xc2ac, 0xc2ad, 0xc2ae, 0xc2af
0xc2b0, 0xc2b1, 0xc2b2, 0xc2b3, 0xc2b4, 0xc2b5, 0xc2b6, 0xc2b7
0xc2b8, 0xc2b9, 0xc2ba, 0xc2bb, 0xc2bc, 0xc2bd, 0xc2be, 0xc2bf
0xc380, 0xc381, 0xc382, 0xc383, 0xc384, 0xc385, 0xc386, 0xc387
0xc388, 0xc389, 0xc38a, 0xc38b, 0xc38c, 0xc38d, 0xc38e, 0xc38f
0xc49e, 0xc391, 0xc392, 0xc393, 0xc394, 0xc395, 0xc396, 0xc397
0xc398, 0xc399, 0xc39a, 0xc39b, 0xc39c, 0xc4b0, 0xc59e, 0xc39f
0xc3a0, 0xc3a1, 0xc3a2, 0xc3a3, 0xc3a4, 0xc3a5, 0xc3a6, 0xc3a7
0xc3a8, 0xc3a9, 0xc3aa, 0xc3ab, 0xc3ac, 0xc3ad, 0xc3ae, 0xc3af
0xc49f, 0xc3b1, 0xc3b2, 0xc3b3, 0xc3b4, 0xc3b5, 0xc3b6, 0xc3b7
0xc3b8, 0xc3b9, 0xc3ba, 0xc3bb, 0xc3bc, 0xc4b1, 0xc59f, 0xc3bf
};

/*
 * converting iso8859-10
 */
int iso8859-10[]={
0xc2a0, 0xc484, 0xc492, 0xc4a2, 0xc4aa, 0xc4a8, 0xc4b6, 0xc2a7
0xc4bb, 0xc490, 0xc5a0, 0xc5a6, 0xc5bd, 0xc2ad, 0xc5aa, 0xc58a
0xc2b0, 0xc485, 0xc493, 0xc4a3, 0xc4ab, 0xc4a9, 0xc4b7, 0xc2b7
0xc4bc, 0xc491, 0xc5a1, 0xc5a7, 0xc5be, 0xe28095, 0xc5ab, 0xc58b
0xc480, 0xc381, 0xc382, 0xc383, 0xc384, 0xc385, 0xc386, 0xc4ae
0xc48c, 0xc389, 0xc498, 0xc38b, 0xc496, 0xc38d, 0xc38e, 0xc38f
0xc390, 0xc585, 0xc58c, 0xc393, 0xc394, 0xc395, 0xc396, 0xc5a8
0xc398, 0xc5b2, 0xc39a, 0xc39b, 0xc39c, 0xc39d, 0xc39e, 0xc39f
0xc481, 0xc3a1, 0xc3a2, 0xc3a3, 0xc3a4, 0xc3a5, 0xc3a6, 0xc4af
0xc48d, 0xc3a9, 0xc499, 0xc3ab, 0xc497, 0xc3ad, 0xc3ae, 0xc3af
0xc3b0, 0xc586, 0xc58d, 0xc3b3, 0xc3b4, 0xc3b5, 0xc3b6, 0xc5a9
0xc3b8, 0xc5b3, 0xc3ba, 0xc3bb, 0xc3bc, 0xc3bd, 0xc3be, 0xc4b8
};

/*
 * converting iso8859-11
 */
int iso8859-11[]={
0xc2a0, 0xe0b881, 0xe0b882, 0xe0b883, 0xe0b884, 0xe0b885, 0xe0b886, 0xe0b887
0xe0b888, 0xe0b889, 0xe0b88a, 0xe0b88b, 0xe0b88c, 0xe0b88d, 0xe0b88e, 0xe0b88f
0xe0b890, 0xe0b891, 0xe0b892, 0xe0b893, 0xe0b894, 0xe0b895, 0xe0b896, 0xe0b897
0xe0b898, 0xe0b899, 0xe0b89a, 0xe0b89b, 0xe0b89c, 0xe0b89d, 0xe0b89e, 0xe0b89f
0xe0b8a0, 0xe0b8a1, 0xe0b8a2, 0xe0b8a3, 0xe0b8a4, 0xe0b8a5, 0xe0b8a6, 0xe0b8a7
0xe0b8a8, 0xe0b8a9, 0xe0b8aa, 0xe0b8ab, 0xe0b8ac, 0xe0b8ad, 0xe0b8ae, 0xe0b8af
0xe0b8b0, 0xe0b8b1, 0xe0b8b2, 0xe0b8b3, 0xe0b8b4, 0xe0b8b5, 0xe0b8b6, 0xe0b8b7
0xe0b8b8, 0xe0b8b9, 0xe0b8ba, 0x0000, 0x0000, 0x0000, 0x0000, 0xe0b8bf
0xe0b980, 0xe0b981, 0xe0b982, 0xe0b983, 0xe0b984, 0xe0b985, 0xe0b986, 0xe0b987
0xe0b988, 0xe0b989, 0xe0b98a, 0xe0b98b, 0xe0b98c, 0xe0b98d, 0xe0b98e, 0xe0b98f
0xe0b990, 0xe0b991, 0xe0b992, 0xe0b993, 0xe0b994, 0xe0b995, 0xe0b996, 0xe0b997
0xe0b998, 0xe0b999, 0xe0b99a, 0xe0b99b, 0x0000, 0x0000, 0x0000, 0x0000
};

/*
 * converting iso8859-13
 */
int iso8859-13[]={
0xc2a0, 0xe2809d, 0xc2a2, 0xc2a3, 0xc2a4, 0xe2809e, 0xc2a6, 0xc2a7
0xc398, 0xc2a9, 0xc596, 0xc2ab, 0xc2ac, 0xc2ad, 0xc2ae, 0xc386
0xc2b0, 0xc2b1, 0xc2b2, 0xc2b3, 0xe2809c, 0xc2b5, 0xc2b6, 0xc2b7
0xc3b8, 0xc2b9, 0xc597, 0xc2bb, 0xc2bc, 0xc2bd, 0xc2be, 0xc3a6
0xc484, 0xc4ae, 0xc480, 0xc486, 0xc384, 0xc385, 0xc498, 0xc492
0xc48c, 0xc389, 0xc5b9, 0xc496, 0xc4a2, 0xc4b6, 0xc4aa, 0xc4bb
0xc5a0, 0xc583, 0xc585, 0xc393, 0xc58c, 0xc395, 0xc396, 0xc397
0xc5b2, 0xc581, 0xc59a, 0xc5aa, 0xc39c, 0xc5bb, 0xc5bd, 0xc39f
0xc485, 0xc4af, 0xc481, 0xc487, 0xc3a4, 0xc3a5, 0xc499, 0xc493
0xc48d, 0xc3a9, 0xc5ba, 0xc497, 0xc4a3, 0xc4b7, 0xc4ab, 0xc4bc
0xc5a1, 0xc584, 0xc586, 0xc3b3, 0xc58d, 0xc3b5, 0xc3b6, 0xc3b7
0xc5b3, 0xc582, 0xc59b, 0xc5ab, 0xc3bc, 0xc5bc, 0xc5be, 0xe28099
};

/*
 * converting iso8859-14
 */
int iso8859-14[]={
0xc2a0, 0xe1b882, 0xe1b883, 0xc2a3, 0xc48a, 0xc48b, 0xe1b88a, 0xc2a7
0xe1ba80, 0xc2a9, 0xe1ba82, 0xe1b88b, 0xe1bbb2, 0xc2ad, 0xc2ae, 0xc5b8
0xe1b89e, 0xe1b89f, 0xc4a0, 0xc4a1, 0xe1b980, 0xe1b981, 0xc2b6, 0xe1b996
0xe1ba81, 0xe1b997, 0xe1ba83, 0xe1b9a0, 0xe1bbb3, 0xe1ba84, 0xe1ba85, 0xe1b9a1
0xc380, 0xc381, 0xc382, 0xc383, 0xc384, 0xc385, 0xc386, 0xc387
0xc388, 0xc389, 0xc38a, 0xc38b, 0xc38c, 0xc38d, 0xc38e, 0xc38f
0xc5b4, 0xc391, 0xc392, 0xc393, 0xc394, 0xc395, 0xc396, 0xe1b9aa
0xc398, 0xc399, 0xc39a, 0xc39b, 0xc39c, 0xc39d, 0xc5b6, 0xc39f
0xc3a0, 0xc3a1, 0xc3a2, 0xc3a3, 0xc3a4, 0xc3a5, 0xc3a6, 0xc3a7
0xc3a8, 0xc3a9, 0xc3aa, 0xc3ab, 0xc3ac, 0xc3ad, 0xc3ae, 0xc3af
0xc5b5, 0xc3b1, 0xc3b2, 0xc3b3, 0xc3b4, 0xc3b5, 0xc3b6, 0xe1b9ab
0xc3b8, 0xc3b9, 0xc3ba, 0xc3bb, 0xc3bc, 0xc3bd, 0xc5b7, 0xc3bf
};

/*
 * converting iso8859-15
 */
int iso8859-15[]={
0xc2a0, 0xc2a1, 0xc2a2, 0xc2a3, 0xe282ac, 0xc2a5, 0xc5a0, 0xc2a7
0xc5a1, 0xc2a9, 0xc2aa, 0xc2ab, 0xc2ac, 0xc2ad, 0xc2ae, 0xc2af
0xc2b0, 0xc2b1, 0xc2b2, 0xc2b3, 0xc5bd, 0xc2b5, 0xc2b6, 0xc2b7
0xc5be, 0xc2b9, 0xc2ba, 0xc2bb, 0xc592, 0xc593, 0xc5b8, 0xc2bf
0xc380, 0xc381, 0xc382, 0xc383, 0xc384, 0xc385, 0xc386, 0xc387
0xc388, 0xc389, 0xc38a, 0xc38b, 0xc38c, 0xc38d, 0xc38e, 0xc38f
0xc390, 0xc391, 0xc392, 0xc393, 0xc394, 0xc395, 0xc396, 0xc397
0xc398, 0xc399, 0xc39a, 0xc39b, 0xc39c, 0xc39d, 0xc39e, 0xc39f
0xc3a0, 0xc3a1, 0xc3a2, 0xc3a3, 0xc3a4, 0xc3a5, 0xc3a6, 0xc3a7
0xc3a8, 0xc3a9, 0xc3aa, 0xc3ab, 0xc3ac, 0xc3ad, 0xc3ae, 0xc3af
0xc3b0, 0xc3b1, 0xc3b2, 0xc3b3, 0xc3b4, 0xc3b5, 0xc3b6, 0xc3b7
0xc3b8, 0xc3b9, 0xc3ba, 0xc3bb, 0xc3bc, 0xc3bd, 0xc3be, 0xc3bf
};

/*
 * converting iso8859-16
 */
int iso8859-16[]={
0xc2a0, 0xc484, 0xc485, 0xc581, 0xe282ac, 0xe2809e, 0xc5a0, 0xc2a7
0xc5a1, 0xc2a9, 0xc898, 0xc2ab, 0xc5b9, 0xc2ad, 0xc5ba, 0xc5bb
0xc2b0, 0xc2b1, 0xc48c, 0xc582, 0xc5bd, 0xe2809d, 0xc2b6, 0xc2b7
0xc5be, 0xc48d, 0xc899, 0xc2bb, 0xc592, 0xc593, 0xc5b8, 0xc5bc
0xc380, 0xc381, 0xc382, 0xc482, 0xc384, 0xc486, 0xc386, 0xc387
0xc388, 0xc389, 0xc38a, 0xc38b, 0xc38c, 0xc38d, 0xc38e, 0xc38f
0xc490, 0xc583, 0xc392, 0xc393, 0xc394, 0xc590, 0xc396, 0xc59a
0xc5b0, 0xc399, 0xc39a, 0xc39b, 0xc39c, 0xc498, 0xc89a, 0xc39f
0xc3a0, 0xc3a1, 0xc3a2, 0xc483, 0xc3a4, 0xc487, 0xc3a6, 0xc3a7
0xc3a8, 0xc3a9, 0xc3aa, 0xc3ab, 0xc3ac, 0xc3ad, 0xc3ae, 0xc3af
0xc491, 0xc584, 0xc3b2, 0xc3b3, 0xc3b4, 0xc591, 0xc3b6, 0xc59b
0xc5b1, 0xc3b9, 0xc3ba, 0xc3bb, 0xc3bc, 0xc499, 0xc89b, 0xc3bf
};
`

**Comment by elFallino** [comment]
Sure, everything in GitHub should stay in english.
I'll have a look later - I guess there are some things I have to understand. The ideas I had seem to be thought too easy :)
But one thing is sure, there need to be a way to leave out unneeded chars. If I need German special chars I do not need all those others that are in between. They take up too much space even if one uses a rather capable system (I am developing on ESP32 atm).

**Comment by pljakobs** [comment]
well yes, of course we can make half-baked solutions but that would mean to create [Mojibake](https://en.wikipedia.org/wiki/Mojibake)

**Comment by elFallino** [comment]
Now re-reading your post after my children are gone to bed I guess I understand what you are writing about (I'm sorry :) ).
So this would not fix my primary problem (incorrect converted fonts: everything is there but it seems that some pixels are missing or are there in addition ... like a bitmap scaled by a odd factor) but is indeed something worth to be done.

I shipped around the utf8-> ISO problematic by using escape sequences in code.
This is something you can do when just want to use some few special chars but surely is a pain in the ass with some other languages.

I am sure I do not completely understand your thoughts on that because I haven't spend a single brain-cell on that issue before.
But I still think that there should be an option to the converter itself to specify which glyphs are converted because in most cases (at least in western europe languages) you do not need more that one third of the 255 available glyphs and so they do not need to be stored into progmem.

This could be done by having the user specifying the glyphs that are wanted within a separate (e.g. .txt) file or passing as an additional parameter instead of defining a range of glyphs.

**Comment by elFallino** [comment]
Here you can see a picture. It compares an original shipped one with a self-converted one.

https://postimg.org/image/6ml1xzfdp/79bfeb7a/

**Comment by pljakobs** [comment]
ah, now I get it, I was under the impression that *only* the umlauts were being butchered. This looks much like rounding errors / dithering errors / pixel misalignment. I had seen that very early on when working with greyscale font rendering and then bad dithering. Did you use the fontconvert tool from this repo? It looks a lot like my old initial version...

**Comment by elFallino** [comment]
I used the one that was shipped with Adafruit_GFX library. I am pretty sure I downloaded it from this git repo. But wouldn't swear so I'll check later to be sure.

Am 9. Januar 2017 16:34:47 MEZ schrieb Peter Jakobs <notifications@github.com>:
>ah, now I get it, I was under the impression that *only* the umlauts
>were being butchered. This looks much like rounding errors / dithering
>errors / pixel misalignment. I had seen that very early on when working
>with greyscale font rendering and then bad dithering. Did you use the
>fontconvert tool from this repo? It looks a lot like my old initial
>version...
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/adafruit/Adafruit-GFX-Library/issues/103#issuecomment-271314885

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pljakobs** [comment]
And you said you're using it on Windows?
I have never myself tested that port - I only work on Linux platforms. Can you try some other font and see if the results are the same?

**Comment by elFallino** [comment]
Yes, I am using it on Windows. Even if I prefer Linux, too.
I'll try another font.

**Comment by elFallino** [comment]
Other fonts look terrible, too. I tried FreeMono and FreeSerif.

**Comment by pljakobs** [comment]
strange. I'm rather consumed by work and other projects right now, but I think I might have to try and recreate this.
I know it's not much help, but others have not reported the same issue, so I wonder what the reason might be. You might want to try and find the issue that resulted in the eventual port over to Windows and ask the fine chap who did that if he has seen similar problems?
Sorry that I cannot be of more help right now.
pj

**Comment by PaintYourDragon** [comment]
The pre-converted example fonts included with GFX were produced on a system with FreeType 2.6.0 installed. Release notes for later versions of FreeType (2.6.4 and 2.7) mention some changes in the default hinting behavior...this may or may not be what you're seeing. Release notes also mention that the "classic" behavior can be configured at compile-time or through the FREETYPE_PROPERTIES environment variable.

**Comment by elFallino** [comment]
Thanks. Good hint.

I tried 
`$ env FREETYPE_PROPERTIES=freetype fontconvert.exe FreeSans.ttf 9 32 252 > FreeSans9pt8b_2.h` (should be the new hinting function)
and
`$ env FREETYPE_PROPERTIES=adobe fontconvert.exe FreeSans.ttf 9 32 252 > FreeSans9pt8b_2.h` (should be the old hinting function)
but both results do not differ (using a diff-tool) and they also do not differ from what I have produced before (the one that looks so bad).

**Comment by PaintYourDragon** [comment]
Suggest maybe installing 2.6, see if any change...can always re-install latest over it if needed.

**Comment by PaintYourDragon** [comment]
Looks like properties syntax for hinting might be:
FREETYPE_PROPERTIES=cff:hinting-engine=adobe
Hard to say for sure. Documentation's a little sparse there and the source is like a billion things to dig through. Well, if earlier release works, maybe that's just the easier thing to do for now.

**Comment by pljakobs** [comment]
thanks @PaintYourDragon, I was unaware of that change and, in fact, hadn't used fontconvert in a while.

**Comment by mertaysoy** [comment]
I have exactly the same issue. Tried list:

freetype 2.7.1 and freetype 2.6.0 
Windows and Mac OS X
"FREETYPE_PROPERTIES=cff:hinting-engine=adobe" and "FREETYPE_PROPERTIES=adobe" 
FreeSans.ttf and FreeSerif.ttf

I tried every combination of the above list but no change.

**Comment by tchapi** [comment]
I know this is an old discussion but I've ran into subpixel alignment problems too using fontconvert and I have made a little handy tool to correct the font if needed — I thought I'd share if it can help others : https://tchapi.github.io/Adafruit-GFX-Font-Customiser/

**Comment by vonnieda** [comment]
I've figured out how to revert to the old behavior. In fontconvert.c, after:

```
	// Init FreeType lib, load font
	if((err = FT_Init_FreeType(&library))) {
		fprintf(stderr, "FreeType init error: %d", err);
		return err;
	}
```

Add:

```
	FT_UInt     interpreter_version = TT_INTERPRETER_VERSION_35;
	FT_Property_Set( library, "truetype",
                                  "interpreter-version",
                                  &interpreter_version );	
```

See https://www.freetype.org/freetype2/docs/reference/ft2-properties.html#interpreter-version for documentation.

This makes a huge difference in the clarity of generated fonts, especially small ones.

**Comment by PaintYourDragon** [comment]
Merged. Thank you for sorting out the fix for this!
