### ISSUE TITLE
Compressed font & significant print speedup

### ISSUE THREAD

**Issue by eltomjan** [adafruit/Adafruit-GFX-Library#113]
Hello all,
 I made interesting improvements of the library on my project - cleared most of fonts data by XORing and adding 2 level bitmap fields, so it takes aprox. 1/3 of bitmap version (big fonts) and improved also printing - I am using a pixel stream similar to clear operation - big & slow SPI data are significantly reduced then...
 Does anyone want these changes too ? (using Adafruit_ILI9340 at the moment)

**Comment by microbuilder** [comment]
Thanks for posting. Please avoid creating multiple similar issues, though, since they generate email alerts for everyone watching the repos (which is a lot of emails in this case). I've filed a comment on the ILI9340 repo regarding the original similar remarks, so I'll close this issue here for now. If you submit a PR, that will help review and track this kind of information in a more manageable way. Thanks!
