### ISSUE TITLE
Error in char map

### ISSUE THREAD

**Issue by holgerlembke** [adafruit/Adafruit-GFX-Library#22]
Today I wanted to write a °C ("degree Celsius"). So I looked up code page 437 and found it should be character number 248. But it did not work.

After some investigation I learned that the characters starting from 177 are shifted due to a missing character in the 176 to 178 range.

For easy reference have a look at the code page in Wikipedia http://en.wikipedia.org/wiki/Code_page_437 and compare it to this photo: http://forum.arduino.cc/index.php/topic,173537.0.html

0xb0/0xb1/0xb2 should have "gray" blocks but 0xb2 is missing.

Solution: in glcdfont.c add a line

```
	0x08, 0x14, 0x2A, 0x14, 0x22,
	0x22, 0x14, 0x2A, 0x14, 0x08,
190	0x95, 0x00, 0x22, 0x00, 0x95,  // <-----------
	0xAA, 0x00, 0x55, 0x00, 0xAA,
	0xAA, 0x55, 0xAA, 0x55, 0xAA,
```
and remove the five bytes at the end.

**Comment by PaintYourDragon** [comment]
Resolved in latest commit. 'Wrong' behavior is still the default, so that all old code will continue to work for those users 100% as they expect. New code can simply call tft.cp437() to switch over to correct Code Page 437 indices for extended ASCII symbols (once, in setup(), is sufficient).

I apologize for how long this has festered. The extreme simplicity of a runtime workaround that doesn't break all existing code just didn't dawn on me. At some point in the future perhaps we can switch this over as the default behavior.

**Comment by hikari-no-yume** [comment]
> Is it really realistic that this had happened that much? I assume that it never happened before. Due to the In-IDE-it-is-different-than-on-display-problem I would assume all users did not see that problem because not using 8-bit-ascii

I know this is an old bug but I want to point out that this happened to me. I noticed that the font was CP437, added a simple UTF-8 to CP437 translation table and then discovered that the box-drawing characters and beyond were incorrectly mapped :(
