### ISSUE TITLE
Best way to restore "State"

### ISSUE THREAD

**Issue by mabbotts9797** [adafruit/Adafruit-GFX-Library#280]
Apologies for raising an Issue. I don't have an issue with the library, it's very well done and documented. I am however struggling with an issue and wondering the best way to approach it (in terms of how the library was written).

Essentially, I need to restore a previous "state" of the OLED display (Lines, Pixels, shapes drawn etc). I have been messing around with the buffer (using the `display.getBuffer()` function ) and attempting to re-draw it as a bitmap but have been unsuccessful. I have also tried making a temporary copy of the type `Adafruit_SSD1306` and attempted to revert back to it, but no dice either.

Is there a way to restore a previous state of a display via buffer or otherwise?

**Comment by PaintYourDragon** [comment]
Rather than handing the getBuffer() data to a bitmap-drawing function, just raw write data into that address the same way you read it, i.e.:

// Hypothetical save-display-contents-to-SD-file:
// (assuming 'file' is an already-open file for writing)
file.write(display.getBuffer(), 1024); // 1024 = assuming 128x64 display

// Hypothetical load-display-contents-from-SD-file:
// (assuming 'file' is an already-open file for reading)
file.read(display.getBuffer(), 1024); // same
display.display(); // Update OLED with new contents from file

Instead of write/read to file, you could memcpy() it to/from another buffer or just about anything. Just the raw bytes, go right at it.

Screen buffer size can be determined with:
WIDTH * ((HEIGHT + 7) / 8))

This is maybe a bit inelegant in that it’s brute-force and makes assumptions about the buffer and how it’s stored (if that ever were to change)…but sometimes you just gotta get stuff done.
