### ISSUE TITLE
Dynamic Display

### ISSUE THREAD

**Issue by viash23** [adafruit/Adafruit-GFX-Library#38]
The ADAFRUIT_GFX/RGBPanelMatrix Library uses the PROGMEM to display the text.
Now how a char/string be displayed dynamically say how the input from keyboard be displayed in the LED matrix panel when being typed??

Please help with some coding logic

**Comment by tdicola** [comment]
Try posting usage questions in the forums at http://forums.adafruit.com/, there are more folks there that can help answer questions there.  You might check out this recent Arduino Mega example that prints a string from RAM (note it only works on the Mega because it needs a lot of RAM): https://github.com/adafruit/RGB-matrix-Panel/blob/master/examples/testshapes_32x64/testshapes_32x64.ino  In general you should just be able to call matrix.print or matrix.println with a string, just like if you were printing to the serial monitor.
